
spring:
  application:
    name: "full-stack"
  datasource:
    url: jdbc:mysql://localhost:3306/reactboot
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update